### ISSUE TITLE
"Unable to extract JS player URL" error with youtube:  won't download 

### ISSUE THREAD

**Issue by subirax** [l1ving/youtube-dl#15]
## Checklist

- [x ] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2020.09.20**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl --verbose --write-description -o "%(title)s (%(id)s).%(ext)s" -f 140 https://www.youtube.com/watch?v=0XOXpWnqXlQ
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--write-description', '-o', '%(title)s (%(id)s).%(ext)s', '-f', '140', 'https://www.youtube.com/watch?v=0XOXpWnqXlQ']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7600-SP0
[debug] exe versions: ffmpeg git-2020-01-24-e931119, ffprobe git-2020-01-24-e931119
[debug] Proxy map: {}
[youtube] 0XOXpWnqXlQ: Downloading webpage
[youtube] 0XOXpWnqXlQ: Downloading embed webpage
ERROR: Unable to extract JS player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\youtube.py", line 2101, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\common.py", line 1010, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract JS player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

Starting a few days ago, many (not all) youtube downloads result in "Unable to extract JS player URL" and won't download.

When the problem started 4 or 5 days ago, it affected about 10% of youtube URLs, but the proportion of failures is steadily rising; now it's about 60% fails.  

Retrying the same URL sometimes results in success, but that's becoming rarer too, even after 4 or 5 tries.

Some URLs that at this moment play correctly online in Chrome browser; these have each been tried several times with YTDL and won't work.   

https://www.youtube.com/watch?v=1MPXDoB6jc8
https://www.youtube.com/watch?v=bGYSPcHO0TI
https://www.youtube.com/watch?v=jH__tVIJWcI
https://www.youtube.com/watch?v=OuIJ9PILV_k

There seems to be no correlation with time of day or any other factor I can think of.  (Except it seemed to start right after the takedown, but that may be coincidence.)

I hope this is helpful.  Thanks!

**Comment by alin-1** [comment]
@subirax Google intentionally try to mess up youtube-dl by slightly changing their YouTube pages. They are well aware of this tool.

**Comment by Booplicate** [comment]
You just need to adjust the regex. In `_real_extract` find `ASSETS_RE`. I set it to `(?:"PLAYER_JS_URL"|"assets":.+?"js"):\s*("[^"]+")`, seems to work.

**Comment by l1ving** [comment]
The regex is already adjusted.

**Comment by subirax** [comment]
Forgive me, but I don't understand.  The same problem is continuing right now.  

I just confirmed it with a couple more attempts:

https://www.youtube.com/watch?v=bGYSPcHO0TI
https://www.youtube.com/watch?v=kK35x1FkqKk

Both of these are live and functional on youtube, but ytdl returns "Unable to extract JS player URL."

Is it just that my ytdl version -- the latest from the now-dead github page - will be updated soon?

Thanks for your patience!

**Comment by l1ving** [comment]
> Is it just that my ytdl version -- the latest from the now-dead github page - will be updated soon?

I am not ytdl-org, I am l1ving. You have to download it from this GitHub page if you want the fixed version.

**Comment by subirax** [comment]
Thanks, l1ving!  Much appreciated.
