### ISSUE TITLE
About the "A copyright-respecting fork of youtube-dl" description

### ISSUE THREAD

**Issue by rbertoche** [l1ving/youtube-dl#16]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

In the short description text for this repo you say that it's "A copyright-respecting fork of youtube-dl".

Is really necessary to imply that youtube-dl was breaching copyrights?

Legally they certainly weren't, in the same way someone that designs a recorder can't be held responsible for crimes commited by the users of his products.

Please consider removing that text as it is. Some of us are contributing to github and RIAA [fraudulent attack on youtube-dl](https://joindiaspora.com/posts/808cf690f8e801381778002590d8e506) even though I'm sure that is not our intention. We should stand together and refuse that software take resposibility for the acts of those that use them.

With that I hope that I'm for our community's best interests.

**Comment by l1ving** [comment]
Fixed.

**Comment by rbertoche** [comment]
Nice!

**Comment by l1ving** [comment]
I did feel a bit iffy on implying it was originally infringing copyright, but I guess the description served it's purpose in getting word out there the source is unharmed.

**Comment by rbertoche** [comment]
Now it doesn't imply that anymore. I sent that question because I see a lot
of people saying stuff like "it was obviously illegal" and such. I wish
there was some way of making everyone know how much of an outrage that
was...
