### ISSUE TITLE
Please generate a tarball release

### ISSUE THREAD

**Issue by solbu** [l1ving/youtube-dl#17]
Hi.

I am trying to package a the new version, but the distro I package for _does not_ package pandoc, so I can't compile.

Since not all distros have pandoc in their repos, you should _also_ ship a tarball release, as generated by «make youtube-dl.tar.gz» and put it on the releases section, not just the compiled binary.
(The original site did just that. :-) )

**Comment by l1ving** [comment]
Resolved
