### ISSUE TITLE
They are hunting for you

### ISSUE THREAD

**Issue by styac** [l1ving/youtube-dl#23]
I'd change something to avoid an automatic search

https://torrentfreak.com/github-warns-users-reposting-youtube-dl-they-could-be-banned-201102/

**Comment by l1ving** [comment]
Please note how they specify "exact copy of the DMCAed content". I don't care either way. This repository was trending on second place for two entire days, with first place being youtube-dlc. Github already knows about it.

**Comment by solbu** [comment]
Not rehasing the closed issue, just wanted to clarify a misunderstanding from @styac.

You should also note that the warning from Github is for posting the entire DMCA'd content as Pull Request against the official dmca repo, It does not refer to any of our forks in any way.
The warning clearly states «_If you commit or post content to this repository that violates our Terms of Service, we will delete that content and may suspend access to your account as well_»

They simply don't want any violation of their terms in their own DMCA repo.
