### ISSUE TITLE
[bilibili] parse error near `&`

### ISSUE THREAD

**Issue by BlackSinny** [l1ving/youtube-dl#26]
my pc environment:mac

first i run 

```
sudo curl -L https://github.com/l1ving/youtube-dl/releases/latest/download/youtube-dl -o /usr/local/bin/youtube-dl
sudo chmod a+rx /usr/local/bin/youtube-dl
``` to download this like readme.md

when i want to download some youtube video,i got 

my script
```

```
youtube-dl https://www.bilibili.com/bangumi/play/ep342777
```
[generic] ep342777: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ep342777: Downloading webpage
[generic] ep342777: Extracting information
WARNING: [generic] ep342777: Failed to parse JSON Invalid control character at: line 11 column 119 (char 562)
ERROR: Unsupported URL: https://www.bilibili.com/bangumi/play/ep342777
```

**Comment by lyiriyah** [comment]
try putting the url in quotes

**Comment by lyiriyah** [comment]
scratch that, bilibili is not a supported website

**Comment by l1ving** [comment]
Oh it's not supported period lol. Well make a proper request to support it.
