### ISSUE TITLE
How do I use latest youtube dl file on windows? It has no .exe file extension.

### ISSUE THREAD

**Issue by goodstuff626** [l1ving/youtube-dl#35]
## Checklist

- [x] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
How do I use latest youtube dl file - 2020.11.10 on windows? It has no .exe file extension.

**Comment by l1ving** [comment]
You can run youtube-dl.py with python. See #22, I don't know how the original maintainers packaged the exe, but there are tools such as py2exe which you can try.
