### ISSUE TITLE
YouTube playlist downloading doesn't work

### ISSUE THREAD

**Issue by ultrasound1372** [l1ving/youtube-dl#36]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.11.10**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: ['--external-downloader', 'aria2c', '--external-downloader-args', '-j 12 -s 12 -x 12 -k 10M --file-allocation falloc']
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', 'best', '-o', '%(uploader)s/%(playlist_title)s/%(title)s.%(ext)s', 'https://www.youtube.com/playlist?list=PLv0jwu7G_DFUoByWSHHoSTlUIxY7VkJLi']
[debug] Encodings: locale cp1252, fs utf-8, out cp1252, pref cp1252
[debug] youtube-dl version 2020.11.10
[debug] Python version 3.7.9 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg N-99363-g5f905e3802-gf8f23a7af7, ffprobe N-99363-g5f905e3802-gf8f23a7af7
[debug] Proxy map: {}
[youtube:playlist] PLv0jwu7G_DFUoByWSHHoSTlUIxY7VkJLi: Downloading webpage
[download] Downloading playlist: PLv0jwu7G_DFUoByWSHHoSTlUIxY7VkJLi
[youtube:playlist] playlist PLv0jwu7G_DFUoByWSHHoSTlUIxY7VkJLi: Downloading 0 videos
[download] Finished downloading playlist: PLv0jwu7G_DFUoByWSHHoSTlUIxY7VkJLi
```

## Description

Atempting to download playlists doesn't seem to work at all on YouTube. I have some batch scripts that download some uploads playlists and others which download specific playlists, both are affected by this bug. Since a channel's uploads get converted into a playlist the same thing seems to happen. As you can see, it doesn't display the name of the playlist, only the ID, and claims the playlist has 0 videos. My config includes aria2 for faster downloading of the videos, and normally I extract audio, but I've avoided the -x, and aria2 never got called. I saw a PR merged recently that fixes the playlists page on a channel I suppose? But either way I still can't download any videos from playlist URLs I already have.

**Comment by l1ving** [comment]
#30
