### ISSUE TITLE
Downloading playlists no longer works

### ISSUE THREAD

**Issue by DeveloperMCD** [l1ving/youtube-dl#37]
## Checklist

- [X] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2020.11.10**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'--force-ipv4', u'--download-archive', u'/mnt/volume_nyc3_01/lsn/downloaded.txt', u'--sleep-interval', u'90', u'--ignore-errors', u'-i', u'-f', u'bestvideo[height<=2160]+bestaudio/best[height<=2160]', u'https://www.youtube.com/c/LifeSiteNewsMedia/videos']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.11.10
[debug] Python version 2.7.17 (CPython) - Linux-4.15.0-112-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Proxy map: {}
[youtube:user] LifeSiteNewsMedia: Downloading channel page
[youtube:playlist] UUYImiD9L0dMycenfBy2al0Q: Downloading webpage
[download] Downloading playlist: UUYImiD9L0dMycenfBy2al0Q
[youtube:playlist] playlist UUYImiD9L0dMycenfBy2al0Q: Downloading 0 videos
[download] Finished downloading playlist: UUYImiD9L0dMycenfBy2al0Q

## Description

Playlists no longer work -- see log above.

**Comment by VinuRajaKumar** [comment]
Downloading a single youtube link works fine. But, playlist items are not.

C:\Users\Vinu Raja Kumar C>youtube-dl -v -f 22/bestvideo[ext=mp4]+bestaudio[ext=m4a]   --verbose        -c -o "G:/youtube/%(playlist_name)s/%(playlist_index)02d %(title)s.%(ext)s" --playlist-start 3 --playlist-end 3 https://www.youtube.com/playlist?list=PLgnQpQtFTOGQ7eZU0tzmyjSV5w5lt28p8
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', '22/bestvideo[ext=mp4]+bestaudio[ext=m4a]', '--verbose', '-c', '-o', 'G:/youtube/%(playlist_name)s/%(playlist_index)02d %(title)s.%(ext)s', '--playlist-start', '3', '--playlist-end', '3', 'https://www.youtube.com/playlist?list=PLgnQpQtFTOGQ7eZU0tzmyjSV5w5lt28p8']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2020.11.10
[debug] Python version 3.6.1 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg N-94057-g1c3ed11893, ffprobe N-94057-g1c3ed11893
[debug] Proxy map: {}
[youtube:playlist] PLgnQpQtFTOGQ7eZU0tzmyjSV5w5lt28p8: Downloading webpage
[download] Downloading playlist: PLgnQpQtFTOGQ7eZU0tzmyjSV5w5lt28p8
[youtube:playlist] playlist PLgnQpQtFTOGQ7eZU0tzmyjSV5w5lt28p8: Downloading 0 videos
[download] Finished downloading playlist: PLgnQpQtFTOGQ7eZU0tzmyjSV5w5lt28p8

**Comment by l1ving** [comment]
#31
