### ISSUE TITLE
Downloading videos

### ISSUE THREAD

**Issue by Michauuu2137** [l1ving/youtube-dl#39]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

For a few days I can't download many songs from more popular creators, before that everything worked fine, and now I get a message with the content: ERROR: Video unavailable. Can it be repaired?

**Comment by l1ving** [comment]
1. Wrong template
2. Probably #31, if you read the error message
