### ISSUE TITLE
Add back original release tags

### ISSUE THREAD

**Issue by unqueued** [l1ving/youtube-dl#4]
I was able to find the original release tags for youtube-dl. I put them into my fork.

You can add them to the repo like this:

	git clone https://github.com/l1ving/youtube-dl
	cd youtube-dl
	git fetch https://github.com/unqueued/youtube-dl --tags
	git push --tags

**Comment by l1ving** [comment]
I'll be at a computer in about an hour, thank you.

**Comment by l1ving** [comment]
Please remind me if I forget btw

**Comment by DaCoolX** [comment]
Consider this the reminder

**Comment by l1ving** [comment]
Done! Thank you
