### ISSUE TITLE
oreilly - only downloads 1 minute of video

### ISSUE THREAD

**Issue by Noman-tufail** [l1ving/youtube-dl#40]
example link
https://learning.oreilly.com/videos/modern-python-solutions/9781787284517/

## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2020.11.10**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by l1ving** [comment]
Fill out the issue template properly.
