### ISSUE TITLE
channel4.com

### ISSUE THREAD

**Issue by PetrusVermaak** [l1ving/youtube-dl#42]
Can someone please tell me how to download [channel4.com](https://www.channel4.com/programmes/come-dine-with-me) videos? No one seems to be able to do it.
 **Very serious about it, willing to pay $50 if anyone can show me how to download & decrypt the content.** _(No I do NOT want to screen record, it takes too long)_
They use widevine drm, and dash stream. You need an account and a vpn with United Kingdom to be able to watch. You can register on their site for free with a fake UK address.

**Comment by l1ving** [comment]
Youtube-dl is not for breaking DRM of any sort.
