### ISSUE TITLE
ERROR: xxx: YouTube said: Unable to extract video data

### ISSUE THREAD

**Issue by enver-haase** [l1ving/youtube-dl#49]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.11.10**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

ehaase@laapin youtube-dl % ./youtube-dl -v "https://www.youtube.com/watch?v=TvuxrLnQz5g"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=TvuxrLnQz5g']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.11.10
[debug] Python version 2.7.16 (CPython) - Darwin-20.1.0-x86_64-i386-64bit
[debug] exe versions: avconv present, avprobe present, ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] TvuxrLnQz5g: Downloading webpage
ERROR: TvuxrLnQz5g: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 1796, in _real_extract
    'YouTube said: %s' % unavailable_message, expected=True, video_id=video_id)
ExtractorError: TvuxrLnQz5g: YouTube said: Unable to extract video data

## Description
See https://github.com/l1ving/youtube-dl/issues/20 - basically the issue is still there with 2020.11.10

**Comment by l1ving** [comment]
Report this in the official repo
