### ISSUE TITLE
Actual working URLs in README

### ISSUE THREAD

**Issue by busybox11** [l1ving/youtube-dl#6]
In playlist and Long Lines policy sections, the URLs are not working.

We might want to add actual working URLs (with legal content, of course) to demonstrate the tool.

**Comment by l1ving** [comment]
See #5

**Comment by busybox11** [comment]
Oh, haven't seen it. Sorry then.

**Comment by Jr7000750** [comment]
Can I use my bithub on Kodi en connect To stream?

**Comment by Jr7000750** [comment]
Spam no it is a helpqueetion

**Comment by l1ving** [comment]
Stop posting spam questions on my repository. This isn't the place to ask.
