### ISSUE TITLE
Include archive of original unmerged pull requests

### ISSUE THREAD

**Issue by unqueued** [l1ving/youtube-dl#7]
I put all of the unmerged pull requests from the original repo into a single archive branch. I think that the original pull requests should be preserved somewhere in this repo, because they contain significant features that were never merged, as the youtube-dl team was way behind on merges.

The archive branch is an orphan branch, which is good because that means you don't have to deal with it once it is there, and you can easily remove it to save space. I don't think merging it with master is a good idea, but I also can't make a pull request for an orphan branch that doesn't exist on your repo.

In order to make a pull request to an orphan branch, an orphan branch needs to be created.

You can do it like this:

```

git clone https://github.com/l1ving/youtube-dl
cd youtube-dl
git checkout --orphan archive/recovered-github-prs
git reset
git commit --allow-empty -m "Initial dummy commit"
git push origin archive/recovered-github-prs

```

The branch itself is located here: https://github.com/unqueued/youtube-dl/tree/archive/recovered-github-prs

I'm happy to re-put things in another format, but I do think that a complete archive should contain the original prs in some form. There are over 4000 branches, some of which contain some really useful code. I was also thinking of just sticking a .bundle or a tarball into an orphan branch instead. The benefit of that would be that it wouldn't potentially clog up the tree, but it would require a few extra steps to unpack, and you couldn't browse the pull requests in context without unpacking them.

**Comment by l1ving** [comment]
Holy wow. In #2 I was complaining about the possibility of them being lost to time, I'm glad someone archived them. I'd appreciate the pulls, thank you!

**Comment by unqueued** [comment]
OK cool. But I just need you or a repository admin to create the empty orphan branch so github will let me make the PR.

I updated the instructions because I missed a step last night.

Another option that doesn't require and merging and bypasses github and doesn't require a dummy commit from you is to just do:

```

git clone git@github.com:l1ving/youtube-dl.git
cd youtube-dl
git remote add unqueued https://github.com/unqueued/youtube-dl
git fetch unqueued
git checkout archive/recovered-github-prs
git push origin archive/recovered-github-prs


```

**Comment by l1ving** [comment]
Unfortunately I'll be away from home for the next 4 hours, but then I'll be able to do it, thanks. Remind me if I haven't done it by then

**Comment by l1ving** [comment]
Done, thank you!

**Comment by unqueued** [comment]
Cool, I will have some more stuff soon. Generating an INDEX.md file for PRs going back a year, to make it really easy to browse in a web interface, and also functioning as a good starting point for rebuilding.

**Comment by l1ving** [comment]
I'm currently trying to push all the prs to branches in separate repos, I got as far as pulling each one to a branch. However, I get this
```
star-youtube-dl % git reset --hard 955
fatal: ambiguous argument '955': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
star-youtube-dl % git push l1ving 955:pr/955
error: src refspec 955 does not match any
error: failed to push some refs to 'github.com:l1ving/youtube-dl-prs.git'
```
I'm not exactly a git wizard and I can't tell what's going on here, do you know what's happening? @unqueued

**Comment by l1ving** [comment]
```
star-youtube-dl % git push l1ving 955:955   
error: src refspec 955 does not match any
error: failed to push some refs to 'github.com:l1ving/youtube-dl-prs.git'
star-youtube-dl % gck 955
error: pathspec '955' did not match any file(s) known to git
```

**Comment by unqueued** [comment]
Off the top of my head... if you have more than one remote, then it only works with --all or --tags, but if you start mapping specific branches then you have to fully qualify what you're trying to push. If you have more than one remote, then it can't infer what it should map a remote branch to. Check out the manual for git-checkout.

One thing you can do, is to first clone the source repo, check out the branches you want, and then push them to the new remote.

You can also just do this:

```
git push DestinationRepo +refs/remotes/SourceRepo/*:refs/heads/* +refs/tags/*:refs/tags/*
```

Without having to check anything out, because it is rewriting the names of the branches.

If you wanted to track from the source repo pr/955 to local branch 955, and then push it back to pr/955 on destination, it doesn't look like you had it checked out.
