### ISSUE TITLE
Move the CI on Travis to travis.com?

### ISSUE THREAD

**Issue by SlySven** [l1ving/youtube-dl#8]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones {**Question: by *bugtracker* do you mean the issues listed in this GitHub project - if not, where?**}

## Question

When are you going to move the CI on Travis from travis.org to travis.com? The need to do so was raised in 2018 and the deadline is the end of 2020 so is getting close: https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom

As it happens there is a probability that this will lose the build histories so you may wish to take additional care to save anything in those that might be of importance to refer back to,,,

**Comment by l1ving** [comment]
I can't see anything [here](https://docs.travis-ci.com/user/migrate/open-source-on-travis-ci-com/) that says you are forced to migrate, but I can do that in a minute.

**Comment by SlySven** [comment]
Maybe, and that has been picked-up on in https://travis-ci.community/t/org-to-com-migration-deadline/10260 but the original posting is clear (my emphasis):
> In an effort to ensure that all of our users - whether you build open-source, public or private repositories - receive regular feature updates, security patches and UX/UI enhancements, **we are announcing that travis-ci.org will be officially closed down completely on December 31st, 2020,** allowing us to focus all our efforts on bringing new features and fixes to travis-ci.com and all of our awesome users like yourself on the travis-ci.com domain.

**Comment by l1ving** [comment]
Ah. Well I already did it, thanks.
